services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=flask:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - flask
  flask:
    build: flask
    # environment: 
    #   - FLASK_SERVER_PORT=9091
        # - FLASK_ENV=development
        # - FLASK_APP=base_gui.py
    volumes:
      - './flask:/src'
    working_dir: /src
    # command: /bin/bash -c "python3 base_gui.py"
    # "flask run" #"python3 base_gui.py"   ==> essayer en mettant gunicorn (dans requirements  gunicorn==20.1.0 puis ligne suivante)
    #CMD ["gunicorn","--timeout","600","-b",":9091","-w","4","cadviewer:app"] 
    # working_dir: /src/app/static
    # command: /bin/bash -c "npm install && npm run dev"
    ports:
        - 5000:5000